### ISSUE TITLE
Licences?

### ISSUE THREAD

**Issue by soullivaneuh** [AngelJumbo/gruvbox-wallpapers#13]
Hi,

I am curious about the licences behind the wallpapers? As far as I searched, you didn't puy any information about that.

Are they free to use in any context?

Thanks!

**Comment by AngelJumbo** [comment]
Hello, I used to have a disclaimer regarding this saying that at any time the owner of any of these images could have me remove their image. I removed the disclaimer because it's been over a year and no one has ever claimed anything, I thought it was pretty obvious that I have no way of knowing the origin of the images (except the ones I drew myself) after all, almost all of these Images are contributions. But If you need to use a specific image outside of your personal scope, I'm sure a reverse search would help you.
